# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:00
from __future__ import unicode_literals

import core.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='A token name must be a string of a size between 1 and 50 characters long and must consist of only alphanumeric characters, underscores and hyphens', regex=re.compile('^[\\w-]{1,50}$'))], verbose_name='Name')),
                ('value', models.CharField(db_index=True, default=core.models.generate_token, max_length=100, validators=[django.core.validators.RegexValidator(message='A token value must be an alphanumeric string of a size between 50 and 100 characters long', regex=re.compile('^[a-zA-Z0-9]{50,100}$'))], verbose_name='Value')),
            ],
        ),
    ]
